//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyDBContext : DbContext
    {
        public PharmacyDBContext()
            : base("name=PharmacyDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblMedicine> tblMedicines { get; set; }
        public virtual DbSet<tblMedicineType> tblMedicineTypes { get; set; }
        public virtual DbSet<tblMedicineUnit> tblMedicineUnits { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblOrderDetail> tblOrderDetails { get; set; }
        public virtual DbSet<tblOtherPayment> tblOtherPayments { get; set; }
        public virtual DbSet<tblPromo> tblPromoes { get; set; }
        public virtual DbSet<tblSupplier> tblSuppliers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWarehouseImport> tblWarehouseImports { get; set; }
        public virtual DbSet<tblWarehouseImportDetail> tblWarehouseImportDetails { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
    }
}
