//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicineSupplier
    {
        public int MedicineSupplierId { get; set; }
        public string MedicineID { get; set; }
        public int SupplierID { get; set; }
        public decimal BidPrice { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblSupplier tblSupplier { get; set; }
        public virtual tblMedicine tblMedicine { get; set; }
    }
}
