//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPromo
    {
        public int PromoID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public Nullable<decimal> PromoPrice { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblMedicine tblMedicine { get; set; }
    }
}
