//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarehouse
    {
        public int WarehouseID { get; set; }
        public int MedicineID { get; set; }
        public double Quantity { get; set; }
        public int SupplierID { get; set; }
        public Nullable<System.DateTime> MinimumExpiredDate { get; set; }
    
        public virtual tblMedicine tblMedicine { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
