//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarehouseImportDetail
    {
        public long ImportDetailID { get; set; }
        public string MedicineID { get; set; }
        public double Quantity { get; set; }
        public decimal Price { get; set; }
        public long ImportID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblMedicine tblMedicine { get; set; }
        public virtual tblWarehouseImport tblWarehouseImport { get; set; }
    }
}
