#HP Soultion Features Turner


#Notify icon switch
HPS_FT_IS_SUPPORT_NOTIFY_ICON=TRUE

#Navigation button switch
HPS_FT_IS_SUPPORT_WINDOW_NAVIGATION_BUTTON_PANEL=TRUE

#Adminstrator change user image
HPS_FT_IS_SUPPORT_ADMIN_CHANGE_USER_IMAGE=TRUE

#Search customer by name
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_NAME=TRUE

#Search customer by phone
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_PHONE=TRUE

#Search customer by email
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_EMAIL=FALSE

#Search customer by address
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_ADRESS=FALSE

#Search medicine by medicine id
HPS_FT_IS_SUPPORT_SEARCH_MEDICINE_BY_ID=TRUE

#Search medicine by medicine name
HPS_FT_IS_SUPPORT_SEARCH_MEDICINE_BY_NAME=TRUE

#Filter medicine by medicine type
HPS_FT_IS_SUPPORT_FILTER_MEDICINE_BY_TYPE=TRUE

#Search warehouseimport by medicine id
HPS_FT_IS_SUPPORT_SEARCH_WAREHOUSE_IMPORT_BY_MEDICINE_ID=TRUE

#Search warehouseimport by medicine name
HPS_FT_IS_SUPPORT_SEARCH_WAREHOUSE_IMPORT_BY_MEDICINE_NAME=TRUE

#Search warehouseimport by supplier name
HPS_FT_IS_SUPPORT_SEARCH_WAREHOUSE_IMPORT_BY_SUPPLIER_NAME=TRUE

#Filter warehouseimport by start date
HPS_FT_IS_SUPPORT_FILTER_WAREHOUSE_IMPORT_BY_START_DATE=TRUE

#Filter warehouseimport by end date
HPS_FT_IS_SUPPORT_FILTER_WAREHOUSE_IMPORT_BY_END_DATE=TRUE
