#HP Soultion Features Turner


#Notify icon switch
HPS_FT_IS_SUPPORT_NOTIFY_ICON=TRUE

#Navigation button switch
HPS_FT_IS_SUPPORT_WINDOW_NAVIGATION_BUTTON_PANEL=TRUE

#Adminstrator change user image
HPS_FT_IS_SUPPORT_ADMIN_CHANGE_USER_IMAGE=TRUE

#Search customer by name
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_NAME=TRUE

#Search customer by phone
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_PHONE=TRUE

#Search customer by email
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_EMAIL=FALSE

#Search customer by address
HPS_FT_IS_SUPPORT_SEARCH_CUSTOMER_BY_ADRESS=FALSE